/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cbms.collaborativeClouds.forms;

import cbms.collaborativeClouds.dbworkers.DatabaseConnector;
import cbms.collaborativeClouds.workers.ImageLocator;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author CollaborativeClouds Software Solutions
 */
public class AddStudent extends javax.swing.JFrame {

    /**
     * Creates new form AddStudent
     */
    public AddStudent() throws ClassNotFoundException, SQLException {
        initComponents();
        setLayout(new BorderLayout());
        setLocationRelativeTo(null);
        ImageLocator mImage=new ImageLocator();
        JLabel background = new JLabel(new ImageIcon(mImage.addStudent));
        this.add(background);
        background.setLayout(new FlowLayout());
        //For FullScreen Window, Uncomment Below Code
        Toolkit tk = Toolkit.getDefaultToolkit();
        int xSize = ((int) tk.getScreenSize().getWidth());
        int ySize = ((int) tk.getScreenSize().getHeight());
        this.setSize(xSize, ySize);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        studentid.setSize(xSize/4,30);
        studentName.setSize(xSize/4, 30);
        branch.setSize(xSize/4, 30);
        semester.setSize(xSize/4, 30);
        routeno.setSize(xSize/4, 30);
        bus_stop.setSize(xSize/4, 30);
        rate.setSize(xSize/4, 30);
        jButton1.setSize(100, 35);
        jButton2.setSize(100, 35);
        add_student_info.setLocation(xSize-xSize/4, ySize/4);
        load_routeno();
        routeno_changed();
        getRate();
    }
    
    public void load_routeno() throws ClassNotFoundException, SQLException{
        DatabaseConnector mDBConnect = new DatabaseConnector();
        String sql_select="select distinct route_no from tbl_bus";
        ResultSet mRoutes=mDBConnect.select_execute(sql_select);
        while(mRoutes.next()){
            routeno.addItem(mRoutes.getString("route_no"));
        }
    }
    public void routeno_changed() throws ClassNotFoundException, SQLException{
        bus_stop.removeAllItems();
        DatabaseConnector mDBConnect = new DatabaseConnector();
        String route_no=routeno.getSelectedItem().toString();
        String sql_select="select bus_stop from tbl_bus where route_no='"+route_no+"'";
        ResultSet mBusStops=mDBConnect.select_execute(sql_select);
        while(mBusStops.next()){
            bus_stop.addItem(mBusStops.getString("bus_stop"));
        }
    }
    
    public void getRate() throws ClassNotFoundException, SQLException{
        DatabaseConnector mDBConnect = new DatabaseConnector();
        String route_no=routeno.getSelectedItem().toString();
        String busStop=bus_stop.getSelectedItem().toString();
        String sql_select="select rate from tbl_bus where route_no='"+route_no+"' and bus_stop='"+busStop+"'";
        ResultSet mRate=mDBConnect.select_execute(sql_select);
        if(mRate.next()){
            rate.setText(mRate.getString("rate"));
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        studentid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        studentName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        branch = new javax.swing.JComboBox();
        semester = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        routeno = new javax.swing.JComboBox();
        bus_stop = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        rate = new javax.swing.JTextField();
        add_student_info = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Student ID:");

        studentid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));

        jLabel2.setText("Student Name:");

        studentName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));

        jLabel3.setText("Branch:");

        jLabel4.setText("Semester:");

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Cancel");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        branch.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        branch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CSE", "ME", "ECE", "EEE", "IT", "CE" }));
        branch.setBorder(null);
        branch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        branch.setOpaque(false);

        semester.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        semester.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        semester.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel5.setText("Route No:");

        jLabel6.setText("Bus Stop:");

        routeno.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        routeno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        routeno.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                routenoItemStateChanged(evt);
            }
        });
        routeno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                routenoActionPerformed(evt);
            }
        });

        bus_stop.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bus_stop.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bus_stop.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                bus_stopItemStateChanged(evt);
            }
        });

        jLabel7.setText("Rate:");

        rate.setEditable(false);

        add_student_info.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        add_student_info.setForeground(new java.awt.Color(204, 0, 0));
        add_student_info.setText("ADD STUDENT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(studentid)
                        .addComponent(studentName)
                        .addComponent(branch, 0, 178, Short.MAX_VALUE)
                        .addComponent(semester, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(routeno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bus_stop, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rate))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(91, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(add_student_info)
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(add_student_info)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(studentid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(studentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(branch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(semester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(routeno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(bus_stop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(rate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String mStudentID = studentid.getText();
        String mStudentName=studentName.getText();
        String mBranch=branch.getSelectedItem().toString();
        String mSemester=semester.getSelectedItem().toString();
        String mRoute = routeno.getSelectedItem().toString();
        String mBusStop=bus_stop.getSelectedItem().toString();
        if(mStudentID!=null && mStudentName!=null && mBranch!=null && mSemester!=null && !mStudentID.equals("") && !mStudentName.equals("") && !mBranch.equals("") && !mSemester.equals("")){
            try {
                String sql_insert="insert into tbl_student values('"+mStudentID+"','"+mStudentName+"','"+mBranch+"',"+mSemester+",'"+mRoute+"','"+mBusStop+"')";
                DatabaseConnector mDBConnector=new DatabaseConnector();
                int status=mDBConnector.insert_execute(sql_insert);
                if(status==1){
                    JOptionPane.showMessageDialog(null, "Succesfully Added");
                    studentName.setText("");
                    studentid.setText("");
                }else{
                    JOptionPane.showMessageDialog(null, "Adding Failed");
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(AddStudent.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Oops!! Something Went Wrong!!");
            } catch (SQLException ex) {
                Logger.getLogger(AddStudent.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Oops!! Something Went Wrong!!");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DashBoard mDBoard=new DashBoard();
        mDBoard.show();
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void routenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_routenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_routenoActionPerformed

    private void routenoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_routenoItemStateChanged
     
        try {
            routeno_changed();
            getRate();
        }catch(Exception err){
            
        }
  
    }//GEN-LAST:event_routenoItemStateChanged

    private void bus_stopItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_bus_stopItemStateChanged
        try {
            // TODO add your handling code here:
            
            getRate();
        }catch(Exception er){
            
        }
        
        
    }//GEN-LAST:event_bus_stopItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AddStudent().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(AddStudent.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(AddStudent.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel add_student_info;
    private javax.swing.JComboBox branch;
    private javax.swing.JComboBox bus_stop;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField rate;
    private javax.swing.JComboBox routeno;
    private javax.swing.JComboBox semester;
    private javax.swing.JTextField studentName;
    private javax.swing.JTextField studentid;
    // End of variables declaration//GEN-END:variables
}
